export const  DESCARGAR_INFORMACION = 'DESCARGAR_INFORMACION'
export const  DESCARGAR_INFORMACION_EXITO = 'DESCARGAR_INFORMACION_EXITO'
export const  DESCARGAR_INFORMACION_ERROR = 'DESCARGAR_INFORMACION_ERROR'
