export const   GET_INFORMATION = 'GET_INFORMATION'
export const   GET_INFORMATION_SUCCESS = 'GET_INFORMATION_SUCCESS'
export const   GET_INFORMATION_ERROR = 'GET_INFORMATION_ERROR'

export const   START_SEARCH_TEXT = 'START_SEARCH_TEXT'
export const   START_SEARCH_DATE = 'START_SEARCH_DATE'
export const   START_SEARCH_NUMBER = 'START_SEARCH_NUMBER'

